# Site Info
title:              "The Monody's Blog"
description:        "Is it just a blog?"
author_name:        "Monody Le"
logo_url:           https://avatars1.githubusercontent.com/u/30283022?v=4

# Site Settings
url:                https://monodyle.github.io
baseurl:            "" # the subpath of your site
url:                "" # the base hostname & protocol for your site, e.g. http://example.com
permalink:          /:title # Post permalink
timezone:           Asia/Ho_Chi_Minh

# Build settings
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Plugins settings
# theme: minima
remote_theme: heiswayi/the-plain

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap