<<<<<<< HEAD
# Site Info
title:              "The Monody's Blog"
description:        "Is it just a blog?"
author_name:        "Monody Le"
logo_url:           https://avatars1.githubusercontent.com/u/30283022?v=4

# Site Settings
url:                https://monodyle.github.io
baseurl:            "" # the subpath of your site
url:                "" # the base hostname & protocol for your site, e.g. http://example.com
permalink:          /:title # Post permalink
timezone:           Asia/Ho_Chi_Minh

# Build settings
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Plugins settings
# theme: minima
remote_theme: heiswayi/the-plain

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
=======
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
remote_theme: heiswayi/the-plain
plugins:
  - jekyll-feed
  - jekyll-remote-theme


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
>>>>>>> ff991efc2e8283b12e84c2582d34b95dc8e77ccf
